### ISSUE TITLE
overlap characters bug on HTML5 IE 11/edge (bounty 150 EUR)

### ISSUE THREAD

**Issue by loudoweb** [openfl/openfl#1273]
Hello,

it seems that `textfields`on **IE 11/edge** don't work properly. Sometimes words overlap on each other.

Example : 

should be : "**best in his or her work,**"

but I've got : 

![bug on IE11](http://img4.hostingpics.net/pics/429027bugopenfltextedge.png)

It is not related with https://github.com/openfl/openfl/pull/1186.
Chrome works perfectly, it is only on IE 11/edge.
This bug seems random because adding some characters on a textfield can fix it or make the bug appears.

**Comment by loudoweb** [comment]
This bug really annoys me a lot. Is there any developer having some experience with openfl textfield to take a bounty (150 EUR, almost 170 USD right now) on this?
I really need this bug fixed before October 2.

**Comment by MSGhero** [comment]
I was going to check it out this weekend when I have some time. Can you give a code sample?

**Comment by loudoweb** [comment]
Ok I will give a sample.

**Comment by loudoweb** [comment]
Here is a sample:
[BountyWordOverlap.zip](https://github.com/openfl/openfl/files/487006/BountyWordOverlap.zip)

I'm using:
**haxe 3.2.0
openfl 4.1.0
lime 3.1.0**

Here is my result:

**Internet Explorer 11**
![bug_openfl_textfield](https://cloud.githubusercontent.com/assets/165190/18745365/24d19a80-80c2-11e6-9b7b-23bb047012dc.png)

**Chrome** (I'm pasting here the result on Chrome to see the difference).
![bug_openfl_textfield_chrome](https://cloud.githubusercontent.com/assets/165190/18745366/24d5f620-80c2-11e6-97ab-72f6dd6d676f.png)

I don't know if everything is related but the purpose of the bounty is to fix the bug where there is no workaround (=> the overlaping between text in html tag and normal text). But I will be glad if everything is fixed :)

**Comment by MSGhero** [comment]
I'm on my phone, but does #1066 impact anything? I'm not familiar with htmlText but yeah I'll check it out this weekend.

**Comment by loudoweb** [comment]
No impact. Thanks for checking it out!

**Comment by jgranick** [comment]
Does this occur with ordinary text, or is it only when changing text formats?

**Comment by loudoweb** [comment]
**Overlapping bug:** (_Are there some words overlapping that mess.._) => maybe it's only when changing text formats. I'm using html tags and `TextField.htmlText`
**Carriage return bug:** (_Trying return to next line..._) => ordinary text from windows line endings utf8 xml file
**Missing first character:** (_Is my next bold..._) => only when changing text format to the last word on a line.

Note: I've put the sentences used in my images right above to help understand what occurs

**Comment by mayakwd** [comment]
Hi @loudoweb, I've fixed two of that issues: overlapping and missing character, but, the carriage return - isn't bug.
You can see same behaviour in the flash player, and i guess it's made in openfl for compatibility. 

I'll make pull request tomorrow.

**Comment by mayakwd** [comment]
For the htmlText you can you <br> tag it's definitely what you need.

**Comment by loudoweb** [comment]
Wow. It seems that you fixed everything (even the carriage return bug :+1: ). Thank you so much.
I'll check tomorrow in my project to test different cases and check if eveything good.
As for the bounty, you can contact me by email (contact  @ lugludum  dot  com)

**Comment by mayakwd** [comment]
There is a explanation (in PR) - why in IE text rendering differents with the same code

**Comment by loudoweb** [comment]
Thanks for your work. I've look further and it doesn't fix every cases. It seems that everything is good now in the sample I've shared but in my project I have still some similar overlap or missing space. I've sent to you by email a new text file for the sample to test. Can you do anything? I think you are very close to succeed. Thanks.

**Comment by loudoweb** [comment]
> There is the explanation (in PR) - why in IE text rendering differents with the same code
I've tried to use integer in `getTextWidth ` for every browser in order to have the same value everywhere and as a result I've got the bug in all browser and not only IE.
**Is there a way to have float values for IE?**

**Comment by mayakwd** [comment]
I have added some measuring improvement, that fixes that bug, for my opinion it's better to rewrite TextEngine, to make code more obvious and clear.

**Comment by loudoweb** [comment]
Ok I understand. I agree for TextEngine, I think it's not clear at all.

Thanks for your update, it fixes the last bug in my sample.

Just one last thing, there is a regression bug in your PR: it breaks the caret position of input textfield. With your PR, the caret position remains on the first index instead of moving after the last character.

**Comment by mayakwd** [comment]
Okay, I'll check it today

**Comment by loudoweb** [comment]
Just a quick message to say that @mayakwd fixed the issue. The bounty is now closed.
I let the issue open until it's merged.
