### ISSUE TITLE
Html text not displayed correctly

### ISSUE THREAD

**Issue by flashultra** [openfl/openfl#2331]
When I have multiline textfield with html text in it, the colors are not displayed correctly on the next line
This was working in the previous openfl version.
Example  code:
```haxe
class Main extends Sprite 
{

	var txt:TextField;
	
	public function new() 
	{
		super();
		
		stage.color = 0xffffff;

		txt = new TextField();
		addChild(txt);
		txt.width = 300;
		txt.height = 200;
		txt.border = true;
		txt.textColor = 0x0;
		txt.multiline = true;
		txt.wordWrap = true;
		
		txt.htmlText = 
		"<p><font color='#cccccc'><b>[user1]:</b></font><font color='#ff0000'>sdfdgsfgsfgsg</font></p>"+
		"<p><font color='#cccccc'><b>[user2]:</b></font><font color='#ff0000'>sdfdgsfgsfgsg</font></p>" +
		"<p><font color='#cccccc'><b>[user3]:</b></font><font color='#ff0000'>sdfdgsfgsfgsg</font></p>";
	}

}
```
Download the project: 
https://drive.google.com/open?id=1mqkMmY-A7mMndewqS_gChuYBjxeqGXAb

Screenshoot:
![htmltext_2020-04-12_12-29-37](https://user-images.githubusercontent.com/13473027/79065568-018cfe00-7cba-11ea-82c6-5ffaa2e51fc0.png)

Versions:
   **OpenFL Command-Line Tools (8.9.6-LpgCLS)**
  **Lime Command-Line Tools (7.7.0)**

Problem exist for all targets ( html5, android , etc.)

**Comment by MSGhero** [comment]
Hmm I thought I fixed this already

**Comment by Neborya** [comment]
It's an issue for single-line text too: https://community.openfl.org/t/openfl-8-9-6-release/12264/3

It appeared after this commit: https://github.com/openfl/openfl/commit/2e41ae67ee4d86efa645191e0a748f0c80919b7b#diff-5c7b085bad85fd6d65abc070daf7aa54
and can bee fixed by commenting this code:
`else if (textFormatRanges.length > 0)
{
	textFormatRanges[textFormatRanges.length - 1].end++;
}`

**Comment by MSGhero** [comment]
Oh I guess I broke it 😅 neither of those lines exist on dev version, so I guess it was reverted. But now I'm curious if the original problem is back...

**Comment by jgranick** [comment]
So the goals are to make `develop` as stable/performant as possible (based on what we already know) and to use `feature/x` branches for additional features and we'll merge later after we have enough have testing

**Comment by jgranick** [comment]
The text changes from `develop-v9` haven't made it into any feature branches yet

**Comment by MSGhero** [comment]
This is fixed on latest dev, not exactly sure which commit did it.

**Comment by MSGhero** [comment]
This is actually not fixed, just hidden in the current dev.
