### ISSUE TITLE
getObjectsUnderPoint() returns wrong value (html5 & neko)

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#419]
Sample code:

``` Haxe
    // in Main (document class)

    public function new() {
        super();    
        addEventListener(Event.ADDED_TO_STAGE, added);
    }

    function added()
    {
        var shape = new Shape();
        shape.graphics.beginFill(0);
        shape.graphics.drawCircle(0, 0, 2);
        this.addChild(shape);

        shape = new Shape();
        shape.graphics.beginFill(0);
        shape.graphics.drawCircle(0, 0, 2);
        this.addChild(shape);

        trace('numChildren is ' + this.numChildren);
        trace('this objects under point count ' + this.getObjectsUnderPoint(new Point()).length);
        trace('stage objects under point count ' + stage.getObjectsUnderPoint(new Point()).length);

        stage.addEventListener(Event.ENTER_FRAME, onFrame);
    }
    function onFrame(e:Event):Void
    {
        stage.removeEventListener(Event.ENTER_FRAME, onFrame);
        trace('After frame event----------------------------');
        trace('this objects under point count ' + this.getObjectsUnderPoint(new Point()).length);
        trace('stage objects under point count ' + stage.getObjectsUnderPoint(new Point()).length);
    }
```

Flash output

```
Main.hx:171: this numChildren : 2
Main.hx:172: this objects under point count 2
Main.hx:173: stage objects under point count 2
Main.hx:183: After frame event----------------------------
Main.hx:184: this objects under point count 2
Main.hx:185: stage objects under point count 2
```

HTML5 canvas output

```
"this numChildren : 2" 
"this objects under point count 1"
"stage objects under point count 0"
"After frame event----------------------------" 
"this objects under point count 1" 
"stage objects under point count 3"
```

Neko output

```
Main.hx:171: this numChildren : 2
Main.hx:172: this objects under point count 0
Main.hx:173: stage objects under point count 0
Main.hx:185: After frame event----------------------------
Main.hx:186: this objects under point count 2
Main.hx:187: stage objects under point count 2
```

I tried to find a way to get correct value and I found ENTER_FRAME solution. But html5 still returns wrong count of objects.

openfl v 2.1.6

**Comment by T1mL3arn** [comment]
I made tests in the debug mode, so TextField for trace() is not included. 

Just some results for html5-canvas target with new fixes.

```Haxe

var shape:Shape = null;
for (i in 0...5)
{
	shape = new Shape();
	shape.graphics.beginFill(0, 1);
	shape.graphics.drawCircle(0, 0, 10 );
	shape.x = shape.y = 100;
	
	this.addChild(shape);
}

trace('under stage (100,100) : ' + stage.getObjectsUnderPoint(new Point(100, 100)).length);

for (i in 0...5)
{
	shape = new Shape();
	shape.graphics.beginFill(0, 1);
	shape.graphics.drawCircle(0, 0, 10 );
	shape.x = shape.y = 0;
	
	this.addChild(shape);
}

trace('under stage (100,100) : ' + stage.getObjectsUnderPoint(new Point(0, 0)).length);
trace('-------------------');

```
before enter_frame
```
"under stage (100,100) : 0" 
"under stage (0,0) : 0"
```
after enter_frame
```
"under stage (100,100) : 0"
"under stage (0,0) : 10"
```

**Comment by jgranick** [comment]
Thank you :smile:

Your new test revealed a different issue. While the `getObjectsUnderPoint` list was much more accurate after the fixes, the coordinates for the shapes were not being calculated properly in the hit test, unless the ENTER_FRAME had occurred after they were created. The transform matrix for Sprite and Shape graphics was not being updated if a render had not occurred. This has been fixed.

I also found a better way to handle the main class, so that we don't have to wait for the ENTER_FRAME. Now instead of hardcoding "stage" to work, I actually have the main class being added to the stage before it's `super ()` function is called. Native v2 still needs the render in order for `getObjectsUnderPoint` to work properly, but now HTML5 and native "next" return the same values before or after. It's the same as Flash now, except Flash still has the extra TextField, you can see it if you trace `stage.getObjectsUnderPoint(new Point(0, 0))` rather than only checking the `length` :smile:

**Comment by T1mL3arn** [comment]
Thank you for fixing it for html5. But it still does not work for Neko - is need to use enter_frame trick as usual. I had to say about that in the previous message. 

And there is the new bug! And the new issue here https://github.com/openfl/openfl/issues/448.
