### ISSUE TITLE
hasEventListener() is not working as expected

### ISSUE THREAD

**Issue by mtari** [openfl/openfl#798]
Once a listener has been registered hasEventListener() always returns true even if you removed the listener.

Using haxe 3.2 with openfl 3.3.0, lime 2.5.3.

**Comment by jgranick** [comment]
I believe this should be fixed now. Would you mind patching your openfl/events/EventDispatcher.hx file with this change to see if it fixes it on your end?

**Comment by mtari** [comment]
I'm afraid it's not fixed, but I will re-check it.

**Comment by jgranick** [comment]
Try the second change, the first wasn't quite right :smile:

**Comment by mtari** [comment]
It is not fixed yet.
After removing the event listener I trace __newEventMap.exists (type) and it returns true when I call hasEventListener.

Is there an issue when you remove the event listener?
